### ISSUE TITLE
 error when running node server.js

### ISSUE THREAD

**Issue by marwilc** [calvinpham95/GameTime#1]
hello friend I get the following errors when I run the node server.js how can this be solved? below are the screenshots:

![unstitled](https://user-images.githubusercontent.com/20113479/46881807-963f4300-ce1a-11e8-9d56-c4030947fa42.png)

**Comment by calvinpham95** [comment]
Hey Marwil, thanks for checking out my project. The backend and the project altogether will probably not work since we no longer have access to the Twilio API and the API we are using to pull sports games.
